version: '3.3'

services:
  app:
    image: aryan-nextapp
    build:  .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles